/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ks.ui;

import com.ks.dbOperations.dbOperations;
import com.ks.ui.addEntreprise;
import com.ks.ui.addEmployee;
import com.ks.ui.travailUI;
import javax.swing.JOptionPane;
import com.ks.pdf.pdfGen;
import com.ks.chart.chart;
import org.jfree.chart.ChartPanel;
import javax.swing.UIManager;
import javax.swing.SwingUtilities;





/**
 *
 * @author thyler
 */
public class dashboardUI extends javax.swing.JFrame {
    private String numEntreprise, nomEntreprise, numEmployee, nomEmployee, adresseEmployee;
    
    public String getNumEntreprise(){
        return this.numEntreprise;
    }
    
    public void setNumEntreprise(String newNumEntreprise){
        this.numEntreprise = newNumEntreprise;
    }
    
    public String getNomEntreprise(){
        return this.nomEntreprise;
    }
    
    public void setNomEntreprise(String newNomEntreprise){
        this.nomEntreprise = newNomEntreprise;
    }
    
    public String getNumEmployee(){
        return this.numEmployee;
    }
    
    public void setNumEmployee(String newNumEmployee){
        this.numEmployee = newNumEmployee;
    }
    
    public String getNomEmployee(){
        return this.nomEmployee;
    }
    
    public void setNomEmployee(String newNomEmployee){
        this.nomEmployee = newNomEmployee;
    }
    
    public String getAdresseEmployee(){
        return this.adresseEmployee;
    }
    
    public void setAdresseEmployee(String newAdresseEmployee){
        this.adresseEmployee = newAdresseEmployee;
    }
    
    
    /**
     * Creates new form dashboardUI
     */
    public dashboardUI() {
        initComponents();
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.gtk.GTKLookAndFeel");
            // Call the updateUI() method on the content pane to apply the new Look and Feel
            getContentPane().setBackground(UIManager.getColor("Panel.background"));
            SwingUtilities.updateComponentTreeUI(getContentPane());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("G-Employee");
        setMaximumSize(new java.awt.Dimension(1075, 575));
        setMinimumSize(new java.awt.Dimension(1075, 575));
        setResizable(false);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setMaximumSize(new java.awt.Dimension(1075, 575));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(1075, 575));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1075, 575));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/thyler/testProjets/netbeans/GestionEmployee/assets/building400x400.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 47, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new dbOperations().listEntreprise());
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 576, 250));

        jLabel2.setFont(new java.awt.Font("Cantarell Extra Bold", 1, 22)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Liste des entreprises");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 267, 34));

        jButton1.setText("Ajouter une entreprise");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 200, 30));

        jButton2.setText("Gerer");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 405, 260, 30));

        jButton3.setText("Enregistrer ");
        jButton3.setEnabled(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 405, 300, 30));

        jButton4.setText("Retirer");
        jButton4.setEnabled(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 300, 30));

        jLabel3.setText("Selectionner un entreprise");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 310, -1));

        jButton5.setText("Annuler selection");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, 260, 30));

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 190, 30));

        jLabel4.setText("Rechercher");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        jButton11.setText("Generer PDF de la liste des entreprises");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, -1, -1));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 590, 520));

        jTabbedPane1.addTab("Entreprises", jPanel3);

        jPanel4.setMaximumSize(new java.awt.Dimension(1075, 575));
        jPanel4.setMinimumSize(new java.awt.Dimension(1075, 575));
        jPanel4.setPreferredSize(new java.awt.Dimension(1075, 575));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setLayout(new java.awt.BorderLayout());
        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 240));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Cantarell Extra Bold", 1, 22)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Liste des employees");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 267, 34));

        jTable2.setModel(new dbOperations().listEmployee());
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 169, 630, 253));

        jButton6.setText("Ajouter un employee");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 122, 228, 34));

        jButton7.setText("Enregistrer");
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 210, -1));

        jButton8.setText("Annuler selection");
        jButton8.setEnabled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 200, -1));

        jLabel7.setText("Selectionner un employee");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 59, -1, -1));

        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        jPanel5.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 200, 34));

        jLabel8.setText("Rechercher");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, -1));

        jButton9.setText("Retirer");
        jButton9.setEnabled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 200, -1));

        jButton10.setText("Generer PDF de la liste des employees");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, -1, -1));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 690, 510));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable3.setModel(new dbOperations().salaireGlob(this.jTextField3.getText())
        );
        jScrollPane3.setViewportView(jTable3);

        jPanel6.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 370, 160));

        jLabel9.setFont(new java.awt.Font("Cantarell", 1, 17)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Etat des salaires globaux des employees");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 370, 30));

        jLabel10.setText("ANNEE:");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 30));

        jTextField3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField3.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });
        jPanel6.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 150, 30));

        jLabel11.setText("MONTANT TOTAL:");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, -1));

        jLabel12.setText("0");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        jButton12.setText("Generer PDF");
        jButton12.setEnabled(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 120, 30));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 370, 280));

        jTabbedPane1.addTab("Employees", jPanel4);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new travailUI(this.getNumEntreprise()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = this.jTable1.getSelectedRow();
        Object id = this.jTable1.getValueAt(row, 0);
        Object nom = this.jTable1.getValueAt(row, 1);
        this.setNumEntreprise(id.toString());
        this.setNomEntreprise(nom.toString());
        this.jButton2.setEnabled(true);
        this.jButton3.setEnabled(true);
        this.jButton4.setEnabled(true);
        this.jButton5.setEnabled(true);
        this.jTextField1.setText(null); 
        this.jButton2.setText("Gerer < "+this.getNomEntreprise()+" >");
        this.jButton3.setText("Enregistrer < "+this.getNomEntreprise()+" >");
        this.jButton4.setText("Retirer < "+this.getNomEntreprise()+" >"); 
        this.jLabel3.setText(null);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(null, "Cette action entrainera la suppression de tous les employees et leurs travails dans "+this.getNomEntreprise()+". Continuer?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            // delete the record from the database
            if(new dbOperations().deleteEntreprise(this.getNumEntreprise())){
                JOptionPane.showMessageDialog(null, "Toutes informations concernant "+this.getNomEntreprise()+" ont ete retirees", "Succes", JOptionPane.INFORMATION_MESSAGE);
                this.jButton2.setEnabled(false);
                this.jButton3.setEnabled(false);
                this.jButton4.setEnabled(false);
                this.jButton5.setEnabled(false);
                this.jTextField1.setText(null); 
                this.jButton2.setText("Gerer");
                this.jButton3.setText("Enregistrer");
                this.jButton4.setText("Retirer");
                this.jLabel3.setText("Selectionner une entreprise");
            }else{
                JOptionPane.showMessageDialog(null, "Une erreur s'est produite", "Erreur", JOptionPane.INFORMATION_MESSAGE);
            }           
        } else {
            // do nothing
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        addEntreprise addForm = new addEntreprise();
        addForm.setParent(this);
        addForm.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
        //this.jPanel8.add(new ChartPanel(new chart().createPieChart("Salaire globale de chaque employee", new dbOperations().getChartDataset())));
    }//GEN-LAST:event_formFocusGained

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        this.jLabel12.setText(new dbOperations().getSalaireGlobTotal()+" Fmg");
        this.jTable1.setModel(new dbOperations().listEntreprise());
        this.jTable2.setModel(new dbOperations().listEmployee());
        this.jTable3.setModel(new dbOperations().salaireGlob(this.jTextField3.getText()));
        this.jPanel8.add(new ChartPanel(new chart().createPieChart("Salaire global de chaque employee", new dbOperations().getChartDataset())));
        
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:                                         
        int selectedRow = this.jTable1.getSelectedRow();
        String previousNumVal = this.getNumEntreprise();
        String previousNomVal = this.getNomEntreprise();
        String newNumVal = this.jTable1.getValueAt(selectedRow,0).toString();
        String newNomVal = this.jTable1.getValueAt(selectedRow,1).toString();
        if(previousNumVal == newNumVal && previousNomVal == newNomVal){
            JOptionPane.showMessageDialog(null, "Aucune modification n'a ete faite", "Erreur", JOptionPane.INFORMATION_MESSAGE);
            this.jTable1.clearSelection();
            this.jButton2.setEnabled(false);
            this.jButton3.setEnabled(false);
            this.jButton4.setEnabled(false);
            this.jButton5.setEnabled(false);
            this.jTextField1.setText(null); 
            this.jButton2.setText("Gerer");
            this.jButton3.setText("Enregistrer");
            this.jButton4.setText("Retirer");
            this.jLabel3.setText("Selectionner une entreprise");
        }else{
            if (newNumVal.matches("^[Ss]\\d{3}$") && newNumVal.trim().length() >= 4) {
                    // input matches the pattern
                if(new dbOperations().checkNumEntreprise(newNumVal.toUpperCase()) && previousNumVal != newNumVal){
                    JOptionPane.showMessageDialog(null, "Ce numero d'entreprise est deja prise", "Erreur", JOptionPane.INFORMATION_MESSAGE);
                    this.jTable1.clearSelection();
                    this.jButton2.setEnabled(false);
                    this.jButton3.setEnabled(false);
                    this.jButton4.setEnabled(false);
                    this.jButton5.setEnabled(false);
                    this.jTextField1.setText(null); 
                    this.jButton2.setText("Gerer");
                    this.jButton3.setText("Enregistrer");
                    this.jButton4.setText("Retirer");
                    this.jLabel3.setText("Selectionner une entreprise");
                }else{
                    if(new dbOperations().updateEntreprise(previousNumVal, newNumVal, newNomVal)){
                        JOptionPane.showMessageDialog(null, "Modification reussie", "Succes", JOptionPane.INFORMATION_MESSAGE);
                        this.jTable1.clearSelection();
                        this.jButton2.setEnabled(false);
                        this.jButton3.setEnabled(false);
                        this.jButton4.setEnabled(false);
                        this.jButton5.setEnabled(false);
                        this.jTextField1.setText(null); 
                        this.jButton2.setText("Gerer");
                        this.jButton3.setText("Enregistrer");
                        this.jButton4.setText("Retirer");
                        this.jLabel3.setText("Selectionner une entreprise");
                    }else{
                        JOptionPane.showMessageDialog(null, "Une erreur s'est produite", "Erreur", JOptionPane.INFORMATION_MESSAGE);
                        this.jTable1.clearSelection();
                        this.jButton2.setEnabled(false);
                        this.jButton3.setEnabled(false);
                        this.jButton4.setEnabled(false);
                        this.jButton5.setEnabled(false);
                        this.jTextField1.setText(null); 
                        this.jButton2.setText("Gerer");
                        this.jButton3.setText("Enregistrer");
                        this.jButton4.setText("Retirer");
                        this.jLabel3.setText("Selectionner une entreprise");
                    }
                }   
            } else {
                JOptionPane.showMessageDialog(null, "Le numero d'entreprise doit suivre le format 'S001'", "Erreur", JOptionPane.INFORMATION_MESSAGE);
                this.jTable1.clearSelection();
                this.jButton2.setEnabled(false);
                this.jButton3.setEnabled(false);
                this.jButton4.setEnabled(false);
                this.jButton5.setEnabled(false);
                this.jTextField1.setText(null); 
                this.jButton2.setText("Gerer");
                this.jButton3.setText("Enregistrer");
                this.jButton4.setText("Retirer");
                this.jLabel3.setText("Selectionner une entreprise");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.jButton2.setEnabled(false);
        this.jButton3.setEnabled(false);
        this.jButton4.setEnabled(false);
        this.jButton5.setEnabled(false);
        this.jButton2.setText("Gerer");
        this.jButton3.setText("Enregistrer");
        this.jButton4.setText("Retirer");
        this.jTextField1.setText(null); 
        this.jLabel3.setText("Selectionner une entreprise");
        this.jTable1.clearSelection();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        if(this.jTextField1.getText().trim().isEmpty()){
            this.jTable1.setModel(new dbOperations().listEntreprise());
        }else{
            this.jTable1.setModel(new dbOperations().searchEntreprise(this.jTextField1.getText()));
        }
        this.jButton2.setEnabled(false);
        this.jButton3.setEnabled(false);
        this.jButton4.setEnabled(false);
        this.jButton5.setEnabled(false);
        this.jButton2.setText("Gerer");
        this.jButton3.setText("Enregistrer");
        this.jButton4.setText("Retirer");
        this.jLabel3.setText("Selectionner une entreprise");
        this.jTable1.clearSelection();
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        this.jButton7.setEnabled(false);
        this.jButton8.setEnabled(false);
        this.jButton9.setEnabled(false);
        this.jTable2.clearSelection();
        this.jLabel7.setText("Selectionner un employee");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        new addEmployee().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        // TODO add your handling code here:
        if(this.jTextField2.getText().trim().isEmpty()){
            this.jTable2.setModel(new dbOperations().listEmployee());
        }else{
            this.jTable2.setModel(new dbOperations().searchEmployee(this.jTextField2.getText()));
        }
        this.jButton7.setEnabled(false);
        this.jButton8.setEnabled(false);
        this.jButton9.setEnabled(false);
        this.jLabel7.setText("Selectionner un employee");
        this.jTable2.clearSelection();
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int row = this.jTable2.getSelectedRow();
        Object id = this.jTable2.getValueAt(row, 0);
        Object nom = this.jTable2.getValueAt(row, 1);
        Object adr = this.jTable2.getValueAt(row, 2);
        this.setNumEmployee(id.toString());
        this.setNomEmployee(nom.toString());
        this.setAdresseEmployee(adr.toString());
        this.jButton7.setEnabled(true);
        this.jButton8.setEnabled(true);
        this.jButton9.setEnabled(true);
        this.jTextField2.setText(null);
        this.jLabel7.setText(null);
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(null, "Cette action entrainera la suppression des informations concernant cet employee et l'ensemble de son travail. Continuer?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            // delete the record from the database
            if(new dbOperations().deleteEmployee(this.getNumEmployee())){
                JOptionPane.showMessageDialog(null, "Toutes informations concernant "+this.getNomEmployee()+" ont ete retirees", "Succes", JOptionPane.INFORMATION_MESSAGE);
                this.jButton7.setEnabled(false);
                this.jButton8.setEnabled(false);
                this.jButton9.setEnabled(false);
                this.jTextField2.setText(null);
                this.jLabel7.setText("Selectionner un employee");
            }else{
                JOptionPane.showMessageDialog(null, "Une erreur s'est produite", "Erreur", JOptionPane.INFORMATION_MESSAGE);
            }           
        } else {
            // do nothing
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        // TODO add your handling code here:
        this.jButton2.setEnabled(false);
        this.jButton3.setEnabled(false);
        this.jButton4.setEnabled(false);
        this.jButton5.setEnabled(false);
        this.jButton2.setText("Gerer");
        this.jButton3.setText("Enregistrer");
        this.jButton4.setText("Retirer");
        this.jLabel3.setText("Selectionner une entreprise");
        this.jTable1.clearSelection();
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
        // TODO add your handling code here:
        this.jButton7.setEnabled(false);
        this.jButton8.setEnabled(false);
        this.jButton9.setEnabled(false);
        this.jTextField2.setText(null);
        this.jLabel7.setText("Selectionner un employee");
        this.jTable2.clearSelection();
    }//GEN-LAST:event_jTextField2FocusGained

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int selectedRow = this.jTable2.getSelectedRow();
        String previousNumVal = this.getNumEmployee();
        String previousNomVal = this.getNomEmployee();
        String previousAdrVal = this.getAdresseEmployee();
        String newNumVal = this.jTable2.getValueAt(selectedRow,0).toString();
        String newNomVal = this.jTable2.getValueAt(selectedRow,1).toString();
        String newAdrVal = this.jTable2.getValueAt(selectedRow,2).toString();
        if(previousNumVal == newNumVal && previousNomVal == newNomVal && previousAdrVal == newAdrVal){
            JOptionPane.showMessageDialog(null, "Aucune modification n'a ete faite", "Erreur", JOptionPane.INFORMATION_MESSAGE);
            this.jTable2.clearSelection();
            this.jButton7.setEnabled(false);
            this.jButton8.setEnabled(false);
            this.jButton9.setEnabled(false);
            this.jTextField1.setText(null);
            this.jLabel7.setText("Selectionner un employee");
        }else{
            if (newNumVal.matches("^[Ee]\\d{3}$") && newNumVal.trim().length() >= 4) {
                    // input matches the pattern
                if(new dbOperations().checkNumEmployee(newNumVal.toUpperCase()) && previousNumVal != newNumVal){
                    JOptionPane.showMessageDialog(null, "Ce numero d'employee est deja prise", "Erreur", JOptionPane.INFORMATION_MESSAGE);
                    this.jTable2.clearSelection();
                    this.jButton7.setEnabled(false);
                    this.jButton8.setEnabled(false);
                    this.jButton9.setEnabled(false);
                    this.jTextField2.setText(null);
                    this.jLabel7.setText("Selectionner un employee");
                }else{
                    if(new dbOperations().updateEmployee(previousNumVal, newNumVal, newNomVal,newAdrVal)){
                        JOptionPane.showMessageDialog(null, "Modification reussie", "Succes", JOptionPane.INFORMATION_MESSAGE);
                        this.jTable2.clearSelection();
                        this.jButton7.setEnabled(false);
                        this.jButton8.setEnabled(false);
                        this.jButton9.setEnabled(false);
                        this.jTextField2.setText(null);
                        this.jLabel7.setText("Selectionner un employee");
                    }else{
                        JOptionPane.showMessageDialog(null, "Une erreur s'est produite", "Erreur", JOptionPane.INFORMATION_MESSAGE);
                        this.jTable2.clearSelection();
                        this.jButton7.setEnabled(false);
                        this.jButton8.setEnabled(false);
                        this.jButton9.setEnabled(false);
                        this.jTextField2.setText(null);
                        this.jLabel7.setText("Selectionner un employee");
                    }
                }   
            } else {
                JOptionPane.showMessageDialog(null, "Le numero d'employee doit suivre le format 'E001'", "Erreur", JOptionPane.INFORMATION_MESSAGE);
                this.jTable2.clearSelection();
                this.jButton7.setEnabled(false);
                this.jButton8.setEnabled(false);
                this.jButton9.setEnabled(false);
                this.jTextField1.setText(null);
                this.jLabel7.setText("Selectionner un employee");
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        String arr[]={};
        String arr2[]={};
        JOptionPane.showMessageDialog(null, "Le fichier est dans '"+new pdfGen().genPdf(this.jTable1,"Entreprise","Liste des entreprises",arr,arr2)+"'", "Succes", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        String arr[]={};
        String arr2[]={};
        JOptionPane.showMessageDialog(null, "Le fichier est dans '"+new pdfGen().genPdf(this.jTable2,"Employee","Liste des employees",arr,arr2)+"'", "Succes", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        // TODO add your handling code here:
        if(this.jTextField3.getText().trim().length() == 4){
            this.jButton12.setEnabled(true);
        }
        else{
            this.jButton12.setEnabled(false);
        }
        this.jTable3.setModel(new dbOperations().salaireGlob(this.jTextField3.getText()));
        this.jLabel12.setText(Integer.toString(new dbOperations().getSalaireGlobTotal(this.jTextField3.getText()))+" Fmg");
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        String arr[]={"ANNEE: "+this.jTextField3.getText()};
        String arr2[]={"MONTANT TOTAL: "+this.jLabel12.getText()};
        //System.out.println(arr2[0]);
        JOptionPane.showMessageDialog(null, "Le fichier est dans '"+new pdfGen().genPdf(this.jTable3,"Employee","Etats des salaires globaux des employees",arr,arr2)+"'", "Succes", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboardUI().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
